/**
 * Quiz report PDF (legacy "Generate PDF" feature). jsPDF is bundled and lazy-loaded (no CDN at runtime).
 * The built-in PDF fonts only cover Latin-1, so all text goes through toPdfSafeText.
 */
import { toPdfSafeText } from '../domain/answer/format';
import type { QuizReport } from '../state/progress';

function pad(n: number): string {
  return String(n).padStart(2, '0');
}

export function reportFileName(name: string, when: Date): string {
  const safe = name.replace(/[^A-Za-z0-9]/g, '') || 'Student';
  return `MathLab_${safe}_${when.getFullYear()}${pad(when.getMonth() + 1)}${pad(when.getDate())}_${pad(when.getHours())}${pad(when.getMinutes())}.pdf`;
}

export function hexToRgb(hex: string): [number, number, number] {
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const n = parseInt(h, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

export async function downloadQuizReport(report: QuizReport, studentName: string, accentHex: string): Promise<void> {
  const [{ jsPDF }, { autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 40;
  const W = doc.internal.pageSize.getWidth();
  const accent = hexToRgb(accentHex === '#ffffff' ? '#111827' : accentHex);
  const good: [number, number, number] = [22, 101, 52];
  const bad: [number, number, number] = [179, 38, 30];
  // brick-style header with studs
  doc.setFillColor(...accent);
  doc.rect(0, 0, W, 84, 'F');
  doc.setFillColor(255, 255, 255);
  for (let x = 24; x < W; x += 36) doc.circle(x, 8, 5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('Math Lab - Quiz Report', margin, 54);
  const when = new Date(report.finishedAt);
  const pct = report.total ? Math.round((report.correct / report.total) * 100) : 0;
  doc.setFontSize(11);
  doc.text(toPdfSafeText(`Name: ${studentName}`), W - margin - 230, 30);
  doc.text(`Attempted: ${when.toLocaleString()}`, W - margin - 230, 48);
  doc.text(`Score: ${report.correct}/${report.total} (${pct}%)${report.endedBy === 'TIME_UP' ? ' - time up' : ''}`, W - margin - 230, 66);
  const rows = report.rows.map((r) => [String(r.index + 1), toPdfSafeText(r.questionText), toPdfSafeText(r.yourText || '-'), toPdfSafeText(r.correctText), r.isCorrect ? 'Correct' : 'Wrong', r.standards.join(', ')]);
  autoTable(doc, {
    startY: 104,
    head: [['#', 'Question', 'Your Answer', 'Correct Answer', 'Result', 'CA Standard']],
    body: rows,
    styles: { cellPadding: 5, fontSize: 9, lineWidth: 0.5, valign: 'middle' },
    headStyles: { fillColor: accent, textColor: [255, 255, 255], fontStyle: 'bold' },
    columnStyles: { 0: { halign: 'center', cellWidth: 24 }, 1: { cellWidth: 190 }, 2: { cellWidth: 80 }, 3: { cellWidth: 90 }, 4: { cellWidth: 52, halign: 'center' }, 5: { cellWidth: 79 } },
    didParseCell: (data) => {
      if (data.section !== 'body') return;
      const row = report.rows[data.row.index];
      if (!row) return;
      if (data.column.index === 2) {
        data.cell.styles.fillColor = row.isCorrect ? [236, 253, 245] : [255, 235, 238];
        data.cell.styles.textColor = row.isCorrect ? good : bad;
      }
      if (data.column.index === 3) {
        data.cell.styles.fillColor = [236, 253, 245];
        data.cell.styles.textColor = good;
      }
      if (data.column.index === 4) {
        data.cell.styles.textColor = row.isCorrect ? good : bad;
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });
  const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 124;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(toPdfSafeText(`Generated by Math Lab. Quiz number ${report.seed} recreates the same questions.`), margin, finalY + 22);
  doc.save(reportFileName(studentName, when));
}
