import type { StandardInfo } from '../types';

const NS1 = 'Know that there are numbers that are not rational, and approximate them by rational numbers.';
const EE1 = 'Work with radicals and integer exponents.';
const EE2 = 'Understand the connections between proportional relationships, lines, and linear equations.';
const EE3 = 'Analyze and solve linear equations and pairs of simultaneous linear equations.';
const F1 = 'Define, evaluate, and compare functions.';
const F2 = 'Use functions to model relationships between quantities.';
const G1 = 'Understand congruence and similarity using physical models, transparencies, or geometry software.';
const G2 = 'Understand and apply the Pythagorean Theorem.';
const G3 = 'Solve real-world and mathematical problems involving volume of cylinders, cones, and spheres.';
const SP1 = 'Investigate patterns of association in bivariate data.';

/** Grade 8 content standards (official CA CCSSM text; long lettered sub-parts lightly abridged). No CA additions in grade 8. */
export const GRADE_8_STANDARDS: readonly StandardInfo[] = [
  {
    code: '8.NS.1',
    grade: '8',
    domain: 'NS',
    cluster: NS1,
    text: 'Know that numbers that are not rational are called irrational. Understand informally that every number has a decimal expansion; for rational numbers show that the decimal expansion repeats eventually, and convert a decimal expansion which repeats eventually into a rational number.',
  },
  {
    code: '8.NS.2',
    grade: '8',
    domain: 'NS',
    cluster: NS1,
    text: 'Use rational approximations of irrational numbers to compare the size of irrational numbers, locate them approximately on a number line diagram, and estimate the value of expressions (e.g., π²). For example, by truncating the decimal expansion of √2, show that √2 is between 1 and 2, then between 1.4 and 1.5, and explain how to continue on to get better approximations.',
  },
  {
    code: '8.EE.1',
    grade: '8',
    domain: 'EE',
    cluster: EE1,
    text: 'Know and apply the properties of integer exponents to generate equivalent numerical expressions. For example, 3² × 3⁻⁵ = 3⁻³ = 1/3³ = 1/27.',
  },
  {
    code: '8.EE.2',
    grade: '8',
    domain: 'EE',
    cluster: EE1,
    text: 'Use square root and cube root symbols to represent solutions to equations of the form x² = p and x³ = p, where p is a positive rational number. Evaluate square roots of small perfect squares and cube roots of small perfect cubes. Know that √2 is irrational.',
  },
  {
    code: '8.EE.3',
    grade: '8',
    domain: 'EE',
    cluster: EE1,
    text: 'Use numbers expressed in the form of a single digit times an integer power of 10 to estimate very large or very small quantities, and to express how many times as much one is than the other. For example, estimate the population of the United States as 3 × 10⁸ and the population of the world as 7 × 10⁹, and determine that the world population is more than 20 times larger.',
  },
  {
    code: '8.EE.4',
    grade: '8',
    domain: 'EE',
    cluster: EE1,
    text: 'Perform operations with numbers expressed in scientific notation, including problems where both decimal and scientific notation are used. Use scientific notation and choose units of appropriate size for measurements of very large or very small quantities. Interpret scientific notation that has been generated by technology.',
  },
  {
    code: '8.EE.5',
    grade: '8',
    domain: 'EE',
    cluster: EE2,
    text: 'Graph proportional relationships, interpreting the unit rate as the slope of the graph. Compare two different proportional relationships represented in different ways. For example, compare a distance-time graph to a distance-time equation to determine which of two moving objects has greater speed.',
  },
  {
    code: '8.EE.6',
    grade: '8',
    domain: 'EE',
    cluster: EE2,
    text: 'Use similar triangles to explain why the slope m is the same between any two distinct points on a non-vertical line in the coordinate plane; derive the equation y = mx for a line through the origin and the equation y = mx + b for a line intercepting the vertical axis at b.',
  },
  {
    code: '8.EE.7',
    grade: '8',
    domain: 'EE',
    cluster: EE3,
    text: 'Solve linear equations in one variable. a. Give examples of linear equations in one variable with one solution, infinitely many solutions, or no solutions; show which is the case by transforming the equation into simpler forms until x = a, a = a, or a = b results. b. Solve linear equations with rational number coefficients, including equations whose solutions require expanding expressions using the distributive property and collecting like terms.',
  },
  {
    code: '8.EE.8',
    grade: '8',
    domain: 'EE',
    cluster: EE3,
    text: 'Analyze and solve pairs of simultaneous linear equations. a. Solutions to a system of two linear equations correspond to points of intersection of their graphs. b. Solve systems of two linear equations in two variables algebraically, and estimate solutions by graphing; solve simple cases by inspection (e.g., 3x + 2y = 5 and 3x + 2y = 6 have no solution). c. Solve real-world and mathematical problems leading to two linear equations in two variables.',
  },
  {
    code: '8.F.1',
    grade: '8',
    domain: 'F',
    cluster: F1,
    text: 'Understand that a function is a rule that assigns to each input exactly one output. The graph of a function is the set of ordered pairs consisting of an input and the corresponding output. (Function notation is not required in grade 8.)',
  },
  {
    code: '8.F.2',
    grade: '8',
    domain: 'F',
    cluster: F1,
    text: 'Compare properties of two functions each represented in a different way (algebraically, graphically, numerically in tables, or by verbal descriptions). For example, given a linear function represented by a table of values and a linear function represented by an algebraic expression, determine which function has the greater rate of change.',
  },
  {
    code: '8.F.3',
    grade: '8',
    domain: 'F',
    cluster: F1,
    text: 'Interpret the equation y = mx + b as defining a linear function, whose graph is a straight line; give examples of functions that are not linear. For example, the function A = s² giving the area of a square as a function of its side length is not linear because its graph contains the points (1,1), (2,4) and (3,9), which are not on a straight line.',
  },
  {
    code: '8.F.4',
    grade: '8',
    domain: 'F',
    cluster: F2,
    text: 'Construct a function to model a linear relationship between two quantities. Determine the rate of change and initial value of the function from a description of a relationship or from two (x, y) values, including reading these from a table or from a graph. Interpret the rate of change and initial value of a linear function in terms of the situation it models, and in terms of its graph or a table of values.',
  },
  {
    code: '8.F.5',
    grade: '8',
    domain: 'F',
    cluster: F2,
    text: 'Describe qualitatively the functional relationship between two quantities by analyzing a graph (e.g., where the function is increasing or decreasing, linear or nonlinear). Sketch a graph that exhibits the qualitative features of a function that has been described verbally.',
  },
  {
    code: '8.G.1',
    grade: '8',
    domain: 'G',
    cluster: G1,
    text: 'Verify experimentally the properties of rotations, reflections, and translations: a. Lines are taken to lines, and line segments to line segments of the same length. b. Angles are taken to angles of the same measure. c. Parallel lines are taken to parallel lines.',
  },
  {
    code: '8.G.2',
    grade: '8',
    domain: 'G',
    cluster: G1,
    text: 'Understand that a two-dimensional figure is congruent to another if the second can be obtained from the first by a sequence of rotations, reflections, and translations; given two congruent figures, describe a sequence that exhibits the congruence between them.',
  },
  {
    code: '8.G.3',
    grade: '8',
    domain: 'G',
    cluster: G1,
    text: 'Describe the effect of dilations, translations, rotations, and reflections on two-dimensional figures using coordinates.',
  },
  {
    code: '8.G.4',
    grade: '8',
    domain: 'G',
    cluster: G1,
    text: 'Understand that a two-dimensional figure is similar to another if the second can be obtained from the first by a sequence of rotations, reflections, translations, and dilations; given two similar two-dimensional figures, describe a sequence that exhibits the similarity between them.',
  },
  {
    code: '8.G.5',
    grade: '8',
    domain: 'G',
    cluster: G1,
    text: 'Use informal arguments to establish facts about the angle sum and exterior angle of triangles, about the angles created when parallel lines are cut by a transversal, and the angle-angle criterion for similarity of triangles.',
  },
  { code: '8.G.6', grade: '8', domain: 'G', cluster: G2, text: 'Explain a proof of the Pythagorean Theorem and its converse.' },
  {
    code: '8.G.7',
    grade: '8',
    domain: 'G',
    cluster: G2,
    text: 'Apply the Pythagorean Theorem to determine unknown side lengths in right triangles in real-world and mathematical problems in two and three dimensions.',
  },
  { code: '8.G.8', grade: '8', domain: 'G', cluster: G2, text: 'Apply the Pythagorean Theorem to find the distance between two points in a coordinate system.' },
  {
    code: '8.G.9',
    grade: '8',
    domain: 'G',
    cluster: G3,
    text: 'Know the formulas for the volumes of cones, cylinders, and spheres and use them to solve real-world and mathematical problems.',
  },
  {
    code: '8.SP.1',
    grade: '8',
    domain: 'SP',
    cluster: SP1,
    text: 'Construct and interpret scatter plots for bivariate measurement data to investigate patterns of association between two quantities. Describe patterns such as clustering, outliers, positive or negative association, linear association, and nonlinear association.',
  },
  {
    code: '8.SP.2',
    grade: '8',
    domain: 'SP',
    cluster: SP1,
    text: 'Know that straight lines are widely used to model relationships between two quantitative variables. For scatter plots that suggest a linear association, informally fit a straight line, and informally assess the model fit by judging the closeness of the data points to the line.',
  },
  {
    code: '8.SP.3',
    grade: '8',
    domain: 'SP',
    cluster: SP1,
    text: 'Use the equation of a linear model to solve problems in the context of bivariate measurement data, interpreting the slope and intercept. For example, in a linear model for a biology experiment, interpret a slope of 1.5 cm/hr as meaning that an additional hour of sunlight each day is associated with an additional 1.5 cm in mature plant height.',
  },
  {
    code: '8.SP.4',
    grade: '8',
    domain: 'SP',
    cluster: SP1,
    text: 'Understand that patterns of association can also be seen in bivariate categorical data by displaying frequencies and relative frequencies in a two-way table. Construct and interpret a two-way table summarizing data on two categorical variables collected from the same subjects. Use relative frequencies calculated for rows or columns to describe possible association between the two variables.',
  },
];
